# Generated by Django 5.1.4 on 2025-01-13 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "user",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
