# Generated by Django 5.1.4 on 2025-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
