version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: come_gone_redis
    restart: always

  web:
    build: .
    container_name: come_gone_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/database
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery_worker:
    build: .
    container_name: come_gone_celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - db_data:/app/database
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery_beat:
    build: .
    container_name: come_gone_celery_beat
    command: celery -A config beat --loglevel=info -s /app/database/celerybeat-schedule
    volumes:
      - .:/app
      - db_data:/app/database
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  db_data: