version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  db_data: